pipeline {
    agent {
        docker  {
            image  "node:${readFile '.nvmrc'}",
            args   '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}
