pipeline {
    agent {
        docker {
            image  "node:18.7.0",
            args   '-p 3000:3000'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}
