pipeline {
    agent {
        docker {
            image 'node:18.7.0'
            args '-p 3000:3000 -p 5000:5000 -u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'node --version'
            }
        }
    }
}
