version: "3.7"
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      PGUSER: admin
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg_test:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: tests
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"
    command: -p 5433
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  # pgadmin:
  #   image: dpage/pgadmin4:4.18
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   links:
  #     - "db:pgsql-server"

  # jenkins: 
  #     image: jenkins/jenkins:lts
  #     privileged: true
  #     user: root
  #     ports:
  #       - 8080:8080
  #       - 50000:50000
  #     container_name: jenkins
  #     volumes:
  #       - jenkins_data:/var/jenkins_home
  #       - /usr/bin/docker:/usr/bin/docker
  #       - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db-data:
    # jenkins_data:
    # pgadmin-data:
networks:
  rabbitmq_go_net:
    driver: bridge
